'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowUp,ArrowDown,ArrowRight,ChevronRight,MapPin,Scan,Camera,Box,RotateCcw,Plus,Minus,Bell,Clock,Check,ShieldCheck} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import type {TryOn,ViewState} from '@/lib/try-on';
const initial:ViewState={ready:false,progress:0,mode:'product',placed:false,busy:false,error:''};
const defaultDrop='2026-09-11T18:00';
export default function Page(){
 const host=useRef<HTMLDivElement>(null),engine=useRef<TryOn|null>(null);const [state,setState]=useState(initial);const [permission,setPermission]=useState(false);const [quickLook,setQuickLook]=useState(false);const [drop,setDrop]=useState(defaultDrop);const [now,setNow]=useState(0);const [saved,setSaved]=useState(false);const [note,setNote]=useState('');
 useEffect(()=>{let dead=false;import('@/lib/try-on').then(({TryOn})=>{if(dead||!host.current)return;try{engine.current=new TryOn(host.current,setState)}catch{setState(s=>({...s,error:'3D could not start. Open this page in Safari and reload.'}))}});setQuickLook(document.createElement('a').relList.supports('ar'));setNow(Date.now());try{const d=localStorage.getItem('drop-demo-time');if(d&&!Number.isNaN(Date.parse(d+'+05:30')))setDrop(d);setSaved(localStorage.getItem('drop-demo-saved')==='yes')}catch{}const timer=setInterval(()=>setNow(Date.now()),1000);return()=>{dead=true;clearInterval(timer);engine.current?.dispose()}},[]);
 const remaining=Math.max(0,Math.floor((Date.parse(drop+':00+05:30')-now)/1000));const live=now>0&&remaining===0;const countdown=[Math.floor(remaining/86400),Math.floor(remaining/3600)%24,Math.floor(remaining/60)%60,remaining%60];
 const back=()=>{engine.current?.product();setNote('')};
 const hold=(x:number,z:number)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);engine.current?.move(x,z)},onPointerUp:()=>engine.current?.stop(),onPointerCancel:()=>engine.current?.stop(),onLostPointerCapture:()=>engine.current?.stop()});
 const save=()=>{setSaved(!saved);try{localStorage.setItem('drop-demo-saved',!saved?'yes':'no')}catch{}setNote(!saved?'Saved on this device. This demo does not send notifications.':'Removed from your saved drops.')};
 return <main className={`app ${state.mode!=='product'?'trying':''} ${state.mode==='camera'?'camera-mode':''}`}>
  {state.mode==='product'&&<header className="brandbar"><div className="brand">zepto<span>CONCEPT</span></div><div className="delivery"><MapPin size={17}/><span>Delivering to <b>Home</b></span></div></header>}
  {state.mode==='product'?<div className="breadcrumb"><span>Hot Wheels collection</span><ChevronRight size={14}/><b>Ballistik</b></div>:<header className="try-header"><button aria-label="Back to product" onClick={back}><ArrowLeft/></button><div><strong>Ballistik in your space</strong><span>{state.mode==='camera'?'Live camera · screen-fixed demo':'Interactive 3D demo'}</span></div><span className="small-3d">3D</span></header>}
  <div className="product-layout">
   <section className="visual"><div ref={host} className="model-host"/>
    {state.mode==='product'&&<><span className="edition-tag">THE COLLECTOR’S DROP <span>01</span></span><span className="model-stamp">BALLISTIK</span><div className="viewer-caption"><RotateCcw size={14}/> Drag to rotate · pinch to explore <span>3D MODEL</span></div></>}
    {!state.ready&&<div className="loader"><Box size={30}/><strong>{state.error?'Couldn’t load your car':'Unboxing Ballistik…'}</strong><p>{state.error||'Loading the real 3D model'}</p><Progress value={state.progress} aria-label="Loading 3D model"/>{state.error&&<button onClick={()=>location.reload()}>Reload</button>}</div>}
   </section>
   {state.mode==='product'&&<section className="product-details"><div className="product-kicker">HOT WHEELS <span>COLLECTOR SERIES</span></div><h1>Small car.<br/>Big main-character energy.</h1><div className="product-name"><h2>Hot Wheels Ballistik</h2><span>1 car · die-cast model</span></div><div className="price"><strong>₹179</strong><span>Illustrative price · campaign demo</span></div>
    <button className="try-button" disabled={!state.ready} onClick={()=>setPermission(true)}><span className="try-icon"><Scan size={27}/></span><span><strong>Try it on your table</strong><small>See it. Place it. Take it for a spin.</small></span><ArrowRight size={21}/></button>
    <div className="drop-card"><div className="drop-heading"><span><Clock size={15}/> {live?'DEMO DROP IS OPEN':'NEXT COLLECTOR’S DROP'}</span><span className="live-dot"/></div><h3>{new Date(drop+':00+05:30').toLocaleString('en-IN',{timeZone:'Asia/Kolkata',weekday:'short',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})} IST</h3><div className="countdown">{countdown.map((v,i)=><div key={i}><strong>{now?String(v).padStart(2,'0'):'--'}</strong><span>{['DAYS','HRS','MIN','SEC'][i]}</span></div>)}</div><p>A little anticipation. A lot of horsepower.</p><button className={saved?'save saved':'save'} onClick={save}>{saved?<Check size={18}/>:<Bell size={18}/>} {saved?'Drop saved on this device':'Save this drop'}</button></div>
    {note&&<p className="inline-note" role="status">{note}</p>}
    <div className="details"><h3>Meet your next shelf favourite.</h3><p>Explore the Ballistik’s sculpted body, detailed wheels and bold finish in 3D. Then bring it into your surroundings for a hands-on preview.</p><div className="feature-row"><Box size={20}/><span><b>Your car, every angle</b><small>Original Sketchfab model with an upright pose.</small></span></div><div className="feature-row"><ShieldCheck size={20}/><span><b>Try before the drop</b><small>No checkout or live inventory in this concept.</small></span></div></div>
    <details className="campaign-settings"><summary>Campaign demo settings</summary><label>Drop date and time (IST)<input type="datetime-local" value={drop} onChange={e=>{if(e.target.value){setDrop(e.target.value);try{localStorage.setItem('drop-demo-time',e.target.value)}catch{}}}}/></label><p>This is an editable example schedule, not an announced Hot Wheels drop.</p></details>
    <footer>Independent Zepto × Hot Wheels campaign concept.<br/><a href="https://sketchfab.com/3d-models/hot-wheels-unleashed-2-ballistik-3e2a310334d649ed8c89b9a60d356d12" target="_blank" rel="noreferrer">Ballistik model by Zorg_Sinister · CC BY 4.0 ↗</a></footer>
   </section>}
  </div>
  {state.mode!=='product'&&<>
   <div className="placement-copy"><span className="status-pill"><span/>{state.placed?'READY TO ROLL':'MAKE ROOM FOR A LITTLE LEGEND'}</span><h2>{state.placed?'Your table. Your test drive.':'Aim at your table.'}</h2><p>{state.mode==='camera'?'Manual camera overlay: keep your phone still. The car is not locked to the real table.':'Place the car, then hold an arrow to move it.'}</p></div>
   {!state.placed?<div className="place-controls"><div className="reticle-text">ALIGN CAR WITH YOUR SURFACE</div><button className="pink-button" onClick={()=>engine.current?.place()}>Place car here <Scan size={19}/></button></div>:<section className="drive-controls"><div className="utility"><button onClick={()=>engine.current?.reset()}><RotateCcw size={18}/><span>Reset</span></button><div className="size-buttons"><button aria-label="Make car smaller" onClick={()=>engine.current?.scale(-.15)}><Minus size={18}/></button><span>Size</span><button aria-label="Make car larger" onClick={()=>engine.current?.scale(.15)}><Plus size={18}/></button></div></div><div className="dpad"><button className="up" aria-label="Move forward" {...hold(0,-1)}><ArrowUp/></button><button className="left" aria-label="Move left" {...hold(-1,0)}><ArrowLeft/></button><span className="pad-center">z</span><button className="right" aria-label="Move right" {...hold(1,0)}><ArrowRight/></button><button className="down" aria-label="Move backward" {...hold(0,1)}><ArrowDown/></button></div><p>HOLD AN ARROW TO DRIVE</p></section>}
   {state.error&&<div className="try-error" role="alert">{state.error}</div>}
  </>}
  <Dialog open={permission} onOpenChange={setPermission}><DialogContent className="permission-dialog"><div className="permission-icon"><Camera size={31}/></div><DialogTitle className="permission-title">Your table is the showroom.</DialogTitle><DialogDescription className="permission-description">Enable your rear camera, line up the car with your table, and use the four arrows to move it.</DialogDescription><div className="camera-explainer"><b>About this iPhone web demo</b><p>Camera play is a screen-fixed overlay. Keep your phone still. For real surface placement, use the separate AR viewer below; driving controls aren’t available inside it.</p></div>{state.error&&<p className="permission-error" role="alert">{state.error}</p>}<button className="pink-button" disabled={state.busy||!state.ready} onClick={async()=>{await engine.current?.enableCamera();if(engine.current?.state.mode==='camera')setPermission(false)}}><Camera size={19}/>{state.busy?'Waiting for camera…':'Enable camera & try it'}</button><button className="outline-button" onClick={()=>{engine.current?.preview();setPermission(false)}}><Box size={18}/> Try without camera</button>{quickLook&&<a className="native-ar" rel="ar" href="/models/ballistik.usdz"><img src="/favicon.svg" width="21" height="21" alt=""/> Place on a real table · iPhone AR ↗</a>}<small className="privacy-note">Camera footage stays on your device.</small></DialogContent></Dialog>
 </main>
}
