import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
export type ViewState={ready:boolean;progress:number;mode:'product'|'preview'|'camera';placed:boolean;busy:boolean;error:string};
export class TryOn{
 state:ViewState={ready:false,progress:0,mode:'product',placed:false,busy:false,error:''};
 scene=new T.Scene();camera=new T.PerspectiveCamera(36,1,.01,60);car=new T.Group();renderer:T.WebGLRenderer;orbit:OrbitControls;shadow:T.Mesh;env:T.WebGLRenderTarget;observer:ResizeObserver;
 stream:MediaStream|null=null;video:HTMLVideoElement|null=null;dead=false;request=0;last=0;direction={x:0,z:0};size=1;angle=0;
 constructor(private host:HTMLElement,private emit:(s:ViewState)=>void){
  this.renderer=new T.WebGLRenderer({alpha:true,antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.3;this.renderer.domElement.className='car-canvas';host.appendChild(this.renderer.domElement);
  this.scene.add(this.car,new T.HemisphereLight(0xffffff,0x8d92ab,2.4));const light=new T.DirectionalLight(0xffffff,4);light.position.set(3,5,3);light.castShadow=true;light.shadow.mapSize.set(1024,1024);light.shadow.normalBias=.015;light.shadow.camera.left=-5;light.shadow.camera.right=5;light.shadow.camera.top=5;light.shadow.camera.bottom=-5;this.scene.add(light);
  const pm=new T.PMREMGenerator(this.renderer),room=new RoomEnvironment();this.env=pm.fromScene(room,.04);this.scene.environment=this.env.texture;pm.dispose();room.dispose();
  this.shadow=new T.Mesh(new T.PlaneGeometry(20,20),new T.ShadowMaterial({opacity:.2}));this.shadow.rotation.x=-Math.PI/2;this.shadow.position.y=-.008;this.shadow.receiveShadow=true;this.scene.add(this.shadow);
  this.orbit=new OrbitControls(this.camera,this.renderer.domElement);this.orbit.enableDamping=true;this.orbit.enablePan=false;this.orbit.minDistance=2.7;this.orbit.maxDistance=5;this.orbit.maxPolarAngle=Math.PI*.47;this.orbit.minPolarAngle=.3;this.orbit.autoRotate=false;
  this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(host);this.product();
  new GLTFLoader().load('/models/ballistik-upright.glb',g=>{if(this.dead){this.disposeTree(g.scene);return}g.scene.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true}});this.car.add(g.scene);this.state.ready=true;this.state.progress=100;this.publish()},e=>{this.state.progress=Math.min(99,Math.round(e.loaded/(e.total||8000000)*100));this.publish()},()=>{this.state.error='The 3D car couldn’t load. Check your connection and reload.';this.publish()});
  this.renderer.setAnimationLoop(this.frame);window.addEventListener('keydown',this.keyDown);window.addEventListener('keyup',this.keyUp);window.addEventListener('blur',this.stop);document.addEventListener('visibilitychange',this.visibility);
 }
 publish(){if(!this.dead)this.emit({...this.state})}
 stop=()=>{this.direction={x:0,z:0}};
 stopCamera(){this.request++;this.stream?.getTracks().forEach(t=>t.stop());this.stream=null;this.video?.pause();if(this.video)this.video.srcObject=null;this.video?.remove();this.video=null}
 product(){this.stopCamera();this.stop();this.state.mode='product';this.state.placed=false;this.state.busy=false;this.state.error='';this.car.position.set(0,0,0);this.car.rotation.set(0,0,0);this.car.scale.setScalar(2.15);this.orbit.enabled=true;this.orbit.target.set(0,.22,0);this.camera.position.set(2.3,1.5,2.7);this.camera.lookAt(this.orbit.target);this.resize();this.publish()}
 preview(){this.stopCamera();this.state.mode='preview';this.state.placed=false;this.state.busy=false;this.state.error='';this.configureDrive();this.publish()}
 configureDrive(){this.stop();this.car.position.set(0,0,0);this.car.rotation.set(0,0,0);this.size=1;this.car.scale.setScalar(1);this.orbit.enabled=false;this.resize()}
 async enableCamera(){if(!this.state.ready||this.state.busy)return;this.stopCamera();const ticket=this.request;this.state.busy=true;this.state.error='';this.publish();try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera unavailable');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});if(this.dead||ticket!==this.request){stream.getTracks().forEach(t=>t.stop());return}this.stream=stream;const video=document.createElement('video');video.autoplay=true;video.muted=true;video.playsInline=true;video.srcObject=stream;video.className='camera-feed';this.video=video;this.host.appendChild(video);await video.play();if(this.dead||ticket!==this.request)return;this.state.mode='camera';this.state.placed=false;this.configureDrive()}catch{if(ticket===this.request){this.stopCamera();this.state.error='Camera access was blocked. Allow camera access in Safari’s website settings, or try the 3D demo.'}}finally{if(!this.dead){this.state.busy=false;this.publish()}}}
 place(){if(!this.state.ready||this.state.mode==='product')return;this.state.placed=true;this.publish()}
 move(x:number,z:number){if(!this.state.placed)return;this.direction={x,z}}
 reset(){this.stop();this.car.position.set(0,0,0);this.car.rotation.set(0,0,0);this.angle=0}
 scale(delta:number){this.size=T.MathUtils.clamp(this.size+delta,.65,1.6);this.car.scale.setScalar(this.size);this.confine()}
 confine(){const limit=Math.max(.12,.95-this.size*.5);this.car.position.x=T.MathUtils.clamp(this.car.position.x,-limit,limit);this.car.position.z=T.MathUtils.clamp(this.car.position.z,-.5,.5)}
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.fov=this.state.mode==='product'?36:45;if(this.state.mode!=='product'){const distance=this.camera.aspect<.75?5.2:4;this.camera.position.set(0,distance*.65,distance*.75);this.camera.lookAt(0,0,0)}this.camera.updateProjectionMatrix()}
 frame=(ms:number)=>{const dt=Math.min(.05,(ms-(this.last||ms))/1000);this.last=ms;if(this.state.mode==='product')this.orbit.update();else if(this.state.placed){const {x,z}=this.direction;if(x||z){const length=Math.hypot(x,z);this.car.position.x+=x/length*dt*.65;this.car.position.z+=z/length*dt*.65;this.confine();this.angle=Math.atan2(x,z);const current=this.car.rotation.y;const delta=Math.atan2(Math.sin(this.angle-current),Math.cos(this.angle-current));this.car.rotation.y+=delta*Math.min(1,dt*12)}}this.renderer.render(this.scene,this.camera)};
 keyDown=(e:KeyboardEvent)=>{if(this.state.mode==='product'||!this.state.placed||e.target instanceof HTMLInputElement)return;const map:Record<string,[number,number]>={ArrowUp:[0,-1],KeyW:[0,-1],ArrowDown:[0,1],KeyS:[0,1],ArrowLeft:[-1,0],KeyA:[-1,0],ArrowRight:[1,0],KeyD:[1,0]};if(map[e.code]){e.preventDefault();this.move(...map[e.code])}};
 keyUp=(e:KeyboardEvent)=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'].includes(e.code))this.stop()};
 visibility=()=>{this.stop();if(document.hidden&&this.state.mode==='camera'){this.preview();this.state.error='Camera paused while you were away. Return to the product page to enable it again.';this.publish()}};
 disposeTree(root:T.Object3D){const textures=new Set<T.Texture>();root.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{Object.values(m).forEach(v=>{if(v instanceof T.Texture)textures.add(v)});m.dispose()})}});textures.forEach(t=>t.dispose())}
 dispose(){this.dead=true;this.stopCamera();this.renderer.setAnimationLoop(null);this.observer.disconnect();this.orbit.dispose();window.removeEventListener('keydown',this.keyDown);window.removeEventListener('keyup',this.keyUp);window.removeEventListener('blur',this.stop);document.removeEventListener('visibilitychange',this.visibility);this.disposeTree(this.scene);this.env.dispose();this.renderer.dispose();this.renderer.domElement.remove()}
}
