import fs from 'node:fs';import assert from 'node:assert/strict';import ts from 'typescript';
const b=fs.readFileSync(new URL('../public/models/ballistik-upright.glb',import.meta.url));const gltf=JSON.parse(b.subarray(20,20+b.readUInt32LE(12)));assert(!gltf.skins?.length,'Model must not depend on skeleton transforms');
let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(const m of gltf.meshes)for(const p of m.primitives){const a=gltf.accessors[p.attributes.POSITION];for(let i=0;i<3;i++){min[i]=Math.min(min[i],a.min[i]);max[i]=Math.max(max[i],a.max[i])}}
const size=max.map((v,i)=>v-min[i]);assert(size[1]<size[0]&&size[0]<size[2]);assert(Math.abs(size[2]-1)<.001);assert(Math.abs(min[1])<.001);assert(gltf.images.every(i=>i.bufferView!==undefined),'Textures must be embedded');
const usdz=fs.readFileSync(new URL('../public/models/ballistik.usdz',import.meta.url));assert.equal(usdz.readUInt32LE(0),0x04034b50);
let source=fs.readFileSync(new URL('../lib/try-on.ts',import.meta.url),'utf8');source=source.replace('constructor(private host:HTMLElement,private emit:(s:ViewState)=>void){',`constructor(private host:HTMLElement,private emit:(s:ViewState)=>void){if((globalThis as any).__test){this.renderer={render:()=>{}} as any;this.orbit={update:()=>{}} as any;return;}`);
let js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText.replace(/from ['"]([^'"]+)['"]/g,(_,id)=>`from '${import.meta.resolve(id)}'`);globalThis.__test=true;const {TryOn}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));const v=new TryOn({},()=>{});v.state.mode='preview';v.state.ready=true;v.move(1,0);assert.equal(v.direction.x,0);v.place();
const step=()=>{for(let i=0;i<10;i++)v.frame((v.last||1)+16)};
for(const [x,z]of[[1,0],[-1,0],[0,1],[0,-1]]){v.reset();v.move(x,z);step();assert(x?v.car.position.x*x>0:v.car.position.z*z>0)}v.stop();const before=v.car.position.clone();step();assert(v.car.position.equals(before));v.move(1,0);for(let i=0;i<100;i++)step();assert(v.car.position.x<=.45);v.scale(10);assert.equal(v.size,1.6);assert(v.car.position.x<=.151);v.scale(-10);assert.equal(v.size,.65);let stopped=false;v.stream={getTracks:()=>[{stop:()=>stopped=true}]};v.stopCamera();assert(stopped&&v.stream===null);console.log('PASS: upright static model, embedded textures, USDZ archive, placement gate, four directions, release stop, visible bounds, scale limits, camera cleanup.');
